### ISSUE TITLE
UML Diagrams

### ISSUE THREAD

**Issue by enzozafra** [CMPUT301F17T12/Quirks#14]
Here are the classes that we came up with during the lab:

User
Friends list
News events
Filters
Habits
Event (each habits have an event)
Drops

We just need to figure out how we want to relate them. Just comment below we missed more classes

**Comment by ahnguyen03** [comment]
During the lab i think User and Friends list would be tied together maybe friends list would extend from user or something and then for Habits and and events these would definitely be tied together. Then with habits and events they would be linked to the user, and then with drops these would be again be linked with the user.

**Comment by enzozafra** [comment]
Turns out we need to have the 'view' classes in the UML diagram. So all the activities that we would need. 

Below are the activities that I think we have.

Login screen
news feed
habits
 - habit list
 - new habit
 - edit/view habit

events
 - events list
 - new event
 - edit/view event

friends list
 - friend requests
 - friend "event" feed

geo maps
drops
 - inventory
 - trade

filters
 - filter list?
 - new filter

**Comment by ThomasTetz** [comment]
Did work on the Events related diagrams. Filters and event editing/viewing will be views in android studio and therefore do not have UML representations.  

Created "UML Diagrams" page in the wiki.

**Comment by Jordan-Lane-Dev** [comment]
Added the Quirks UML to the UML Diagrams page in the wiki. As Thomas said, the habit creation / editing will be Views in android studio and therefore do not have UML representations.

**Comment by enzozafra** [comment]
we done i think
